---
- name: Include install tasks
  include_tasks: install.yml

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Include secure tasks
  include_tasks: secure.yml

- name: Include user creation tasks
  include_tasks: users.yml
