---
- name: Ensure Python packages required on control node
  delegate_to: localhost
  run_once: true
  block:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true

    - name: Install passlib on control node
      pip:
        name: passlib
        executable: pip3
- include_tasks: install.yml
- include_tasks: secure.yml
- include_tasks: users.yml

- name: Copy PostgreSQL configuration file from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
