---
- include_tasks: install.yml
- include_tasks: secure.yml
- name: Get installed PostgreSQL version
  command: psql --version
  register: pg_version_raw
  changed_when: false
  become: true

- name: Extract PostgreSQL major version
  set_fact:
    pg_version: "{{ pg_version_raw.stdout.split(' ')[-1].split('.')[0] }}"

- name: Ensure PostgreSQL config directory exists
  file:
    path: "/etc/postgresql/{{ pg_version }}/main"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true
- name: Render postgresql.conf from template
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/main/postgresql.conf  # Adjust version if needed
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
- include_tasks: users.yml
- include_tasks: rotate_passwords.yml
