---
- name: Ensure apt cache is updated
  apt:
    update_cache: true
  become: true

- name: Ensure required system dependencies are installed
  apt:
    name:
      - gnupg
      - lsb-release
      - ca-certificates
      - curl
    state: present
  become: true

- name: Add PostgreSQL APT repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: "pgdg"
    state: present
  become: true

- name: Install PostgreSQL and contrib packages
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
  become: true

- name: Install Python dependencies for Ansible PostgreSQL modules
  apt:
    name:
      - python3-pip
      - libpq-dev
      - python3-psycopg2
    state: present
  become: true

- name: Ensure psycopg2-binary is installed (fallback for newer Python versions)
  pip:
    name: psycopg2-binary
    executable: pip3
  become: true

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true
  become: true
