---
# Precompute the MD5 password hash (format: md5 + md5(password + username))
# Example: password = "admin", username = "postgres"
# echo -n 'adminpostgres' | md5sum => 5c1bfb887d472ba496d7d71b0b94b4ec
# Final hash to use: md55c1bfb887d472ba496d7d71b0b94b4ec

- name: Set admin password hash fact
  set_fact:
    postgres_admin_password_hashed: "md55c1bfb887d472ba496d7d71b0b94b4ec"

# Install and configure PostgreSQL on the target VPS
- include_tasks: install.yml

- include_tasks: secure.yml

- include_tasks: users.yml

- include_tasks: rotate_passwords.yml

- name: Copy PostgreSQL configuration file from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
