---
# Step 1: Install PostgreSQL and required system packages
- name: Include install tasks
  include_tasks: install.yml

# Step 2: Get installed PostgreSQL version
- name: Get installed PostgreSQL version
  command: psql --version
  register: pg_version_raw
  changed_when: false
  become: true

# Step 3: Extract major version (e.g. 15 from 15.6)
- name: Extract PostgreSQL major version
  set_fact:
    pg_version: "{{ pg_version_raw.stdout.split(' ')[-1].split('.')[0] }}"

# Step 4: Ensure config directory exists
- name: Ensure PostgreSQL config directory exists
  file:
    path: "/etc/postgresql/{{ pg_version }}/main"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true

# Step 5: Apply postgresql.conf template
- name: Render postgresql.conf from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true

# Step 6: Secure PostgreSQL
- name: Include secure configuration tasks
  include_tasks: secure.yml

# Step 7: Create users/databases
- name: Include user creation tasks
  include_tasks: users.yml

# Step 8: Rotate DB user passwords (optional)
- name: Include password rotation logic
  include_tasks: rotate_passwords.yml
