---
- name: Create virtual environment for control dependencies
  delegate_to: localhost
  run_once: true
  ansible.builtin.command:
    cmd: python3 -m venv ~/.ansible_venv
  args:
    creates: ~/.ansible_venv/bin/activate

- name: Install passlib in virtualenv
  delegate_to: localhost
  run_once: true
  ansible.builtin.command:
    cmd: ~/.ansible_venv/bin/pip install passlib
  environment:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"

- include_tasks: install.yml
- include_tasks: secure.yml
- include_tasks: users.yml

- name: Copy PostgreSQL configuration file from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
