---
- include_tasks: install.yml
- include_tasks: secure.yml
- include_tasks: users.yml

- name: Copy PostgreSQL configuration file from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
