---
# Control node: Ensure passlib is available for hashing
- name: Ensure Python venv exists on control node
  delegate_to: localhost
  run_once: true
  command: python3 -m venv ~/.ansible_venv
  args:
    creates: ~/.ansible_venv/bin/activate

- name: Install passlib in venv on control node
  delegate_to: localhost
  run_once: true
  command: ~/.ansible_venv/bin/pip install passlib
  environment:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"

# Control node: Ensure password hash filter works using Python from venv
- name: Hash PostgreSQL password on control node
  delegate_to: localhost
  run_once: true
  set_fact:
    postgres_admin_password_hashed: "{{ 'admin' | password_hash('md5') }}"

# Install and configure PostgreSQL on the target VPS
- include_tasks: install.yml

- include_tasks: secure.yml

- include_tasks: users.yml

- include_tasks: rotate_passwords.yml

- name: Copy PostgreSQL configuration file from template
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL
  become: true
