---
- name: Get installed PostgreSQL version
  command: psql -V
  register: pg_version_raw
  changed_when: false
  become: true

- name: Extract PostgreSQL major version
  set_fact:
    pg_version: "{{ pg_version_raw.stdout.split(' ')[-1].split('.')[0] }}"

- name: Include install tasks
  include_tasks: install.yml

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Include secure tasks
  include_tasks: secure.yml

- name: Include user creation tasks
  include_tasks: users.yml
