---
- name: Set PostgreSQL admin password
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ postgres_admin_password_hashed }}"

- name: Configure `pg_hba.conf` to use md5 authentication
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32\s+'
    line: 'host all all 127.0.0.1/32 md5'
    state: present
  notify: Restart PostgreSQL
  become: true
