---
- name: Set PostgreSQL admin password
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ root_password }}"

- name: Allow remote connections in postgresql.conf
  lineinfile:
    path: "/etc/postgresql/14/main/postgresql.conf"
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
  become: true
  notify: Restart PostgreSQL
