---
- name: Create application database user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password_hash }}"
    role_attr_flags: CREATEDB,LOGIN

- name: Create application database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ app_db }}"
    owner: "{{ db_user }}"
