# - name: Compute hashed PostgreSQL user password
#   set_fact:
#     db_password_hash: "md5{{ (db_password) | hash('md5') }}"
#   no_log: true

- name: Create application database user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  no_log: true

- name: Create application database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ database }}"
    owner: "{{ db_user }}"
