---
- name: Ensure PostgreSQL database is created
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ pg_app_db }}"
    encoding: "UTF8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"
    state: present

- name: Ensure PostgreSQL application user is created
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ pg_app_user }}"
    password: "{{ pg_app_password }}"
    encrypted: true
    role_attr_flags: "LOGIN"
    state: present

- name: Grant all privileges on database to application user
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ pg_app_db }}"
    roles: "{{ pg_app_user }}"
    type: database
    privs: ALL
    state: present
