---
- name: Create application database user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ app_password | password_hash('md5') }}"
    role_attr_flags: CREATEDB,LOGIN

- name: Create application database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ app_db }}"
    owner: "{{ database }}"
