---
roles:
  - name: geerlingguy.mysql
    version: 3.3.0  # Optional, but recommended
  - name: geerlingguy.postgresql
    version: 3.1.0  # Optional

collections:
  - name: community.postgresql
  - name: community.mysql
