- name: Test MySQL root login
  hosts: dbservers
  become: yes
  vars_files:
    - ../group_vars/vault.yml  # Adjust path if needed
  tasks:
    - name: Verify MySQL root login from target system
      shell: |
        mysql -u root -p'{{ mysql_root_password }}' -h 127.0.0.1 -e "SHOW DATABASES;"
      register: mysql_login_check
      ignore_errors: yes
      changed_when: false

    - name: Print MySQL login check output
      debug:
        var: mysql_login_check
