---
# This task assumes the following variables are already available:
# - parsed_env_vars (loaded from emr.env)
# - secrets (loaded from emr-secrets.env.vault)
# - service_name (e.g., "emr")

- name: Ensure service directory exists
  file:
    path: "/opt/{{ service_name }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  tags: export_env

- name: Export merged env vars into /opt/{{ service_name }}/.env
  copy:
    dest: "/opt/{{ service_name }}/.env"
    content: |
      {% for key, value in parsed_env_vars.items() %}
      {{ key }}={{ value }}
      {% endfor %}
      {% for key, value in secrets.items() %}
      {{ key }}={{ value }}
      {% endfor %}
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: export_env
- name: Create systemd service file for EMR if JAR exists
  template:
    src: emr.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  when: jar_exists.stat.exists
  notify: Restart {{ service_name }}
  become: true
  tags: service

- name: Check if JAR exists
  stat:
    path: "/opt/{{ service_name }}/{{ service_name }}.jar"
  register: jar_exists
  tags: service

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: true
  tags: service

- name: Enable {{ service_name }} service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
  become: true
  when: jar_exists.stat.exists
  tags: service

- name: Start {{ service_name }} if not running
  systemd:
    name: "{{ service_name }}"
    state: started
  become: true
  when: jar_exists.stat.exists
  tags: service


- name: Debug exported .env file (optional)
  shell: cat /opt/{{ service_name }}/.env
  register: env_file_output
  changed_when: false
  become: true
  tags: [debug, export_env]

- name: Show contents of exported .env file (optional)
  debug:
    var: env_file_output.stdout
  tags: [debug, export_env]
