- name: Read service .env file as raw lines
  slurp:
    src: "/cob-env-config/{{ env_name }}/{{ service_name }}/service-{{ service_name }}.env"
  register: slurped_service_env

- name: Set raw_service_env_lines
  set_fact:
    raw_service_env_lines: "{{ slurped_service_env.content | b64decode | split('\n') }}"

- name: Convert raw_service_env_lines to dictionary
  set_fact:
    parsed_service_env_vars: "{{ parsed_service_env_vars | default({}) | combine({ item.split('=')[0]: item.split('=')[1] }) }}"
  loop: "{{ raw_service_env_lines | select('match', '^[^#\\s].*=.*$') }}"
  when: "'=' in item"

- name: Load service secrets
  slurp:
    src: "/cob-env-config/{{ env_name }}/{{ service_name }}/service-{{ service_name }}-secrets.env.vault"
  register: slurped_service_vault

- name: Decode service secrets
  set_fact:
    service_secrets: "{{ slurped_service_vault.content | b64decode | from_yaml }}"

- name: Write combined .env file to VPS
  copy:
    dest: "/opt/{{ service_name }}/.env"
    content: |
      {% for k, v in parsed_service_env_vars.items() %}
      {{ k }}={{ v }}
      {% endfor %}
      {% for k, v in service_secrets.items() %}
      {{ k }}={{ v }}
      {% endfor %}
    owner: root
    group: root
    mode: '0644'
  become: true
