# Load infra config for Ansible
# Clone config repo locally (controller)
- name: Clone cob-env-config repo to controller
  git:
    repo: "https://github.com/mmadel/cob-environment-configuration.git"
    dest: "./cob-env-config"
    update: yes
  delegate_to: localhost
  run_once: true
  tags: env_config
  
- name: Read infra .env file as raw lines
  slurp:
    src: "/cob-env-config/{{ env_name }}/{{ service_name }}/infra-{{ service_name }}.env"
  register: slurped_infra_env

- name: Set raw_infra_env_lines
  set_fact:
    raw_infra_env_lines: "{{ slurped_infra_env.content | b64decode | split('\n') }}"

- name: Convert raw_infra_env_lines to dictionary
  set_fact:
    parsed_infra_env_vars: "{{ parsed_infra_env_vars | default({}) | combine({ item.split('=')[0]: item.split('=')[1] }) }}"
  loop: "{{ raw_infra_env_lines | select('match', '^[^#\\s].*=.*$') }}"
  when: "'=' in item"

- name: Export infra vars
  set_fact:
    db_user: "{{ parsed_infra_env_vars.DB_USER }}"
    databases: "{{ parsed_infra_env_vars.DATABASE.split(',') }}"
    # Add more as needed

- name: Load infra secrets
  slurp:
    src: "/cob-env-config/{{ env_name }}/{{ service_name }}/infra-{{ service_name }}-secrets.env.vault"
  register: slurped_infra_vault

- name: Decode infra secrets
  set_fact:
    secrets: "{{ slurped_infra_vault.content | b64decode | from_yaml }}"

- name: Export infra secrets
  set_fact:
    db_password: "{{ secrets.db_password | default('') }}"
    root_password: "{{ secrets.root_password | default('') }}"
