---
# Inputs required: 'env_name' and 'service_name' should be defined before this task is imported.

# - name: Clone cob-env-config repo
#   git:
#     repo: "https://github.com/mmadel/cob-environment-configuration.git"
#     dest: "/cob-env-config"
#     update: yes
#   tags: env_config

- name: Define env_file_path from env_name and service_name
  set_fact:
    env_file_path: "/cob-env-config/{{ env_name }}/{{ service_name }}/{{ service_name }}.env"
  tags: env_config

- name: Read .env file content from remote VPS
  slurp:
    src: "{{ env_file_path }}"
  register: slurped_env_file
  tags: env_config

- name: Set raw_env_lines from base64-decoded content
  set_fact:
    raw_env_lines: "{{ slurped_env_file['content'] | b64decode | splitlines() }}"
  tags: env_config

- name: Parse raw .env lines into key=value pairs
  set_fact:
    raw_env_vars: >-
      {{
        raw_env_lines
        | reject('match', '^#')       # skip comments
        | reject('match', '^\\s*$')   # skip blank lines
        | map('regex_replace', '^\\s*(.*?)\\s*=\\s*(.*?)\\s*$', '\\1=\\2')
        | map('split', '=', 1)
        | items2dict
      }}
  tags: env_config

- name: Debug raw_env_vars (optional)
  debug:
    var: raw_env_vars

# Convert list of "KEY=VALUE" to dict
- name: Convert raw_env_vars to dictionary
  set_fact:
    parsed_env_vars: "{{ raw_env_vars | map('split', '=', 1) | items2dict }}"
  tags: env_config

# Export needed plain values
- name: Export parsed env vars
  set_fact:
    db_user: "{{ parsed_env_vars.DB_USER }}"
    databases: "{{ parsed_env_vars.DATABASE.split(',') }}"
    # Add more as needed: parsed_env_vars.SOME_OTHER_KEY
  tags: env_config

# Load encrypted vars from Vault (YAML)
- name: Load encrypted secrets from vault
  include_vars:
    file: "/cob-env-config/{{ env_name }}/{{ service_name }}/{{ service_name }}-secrets.env.vault"
    name: secrets
  tags: env_config

# Flatten secrets for easy access
- name: Export secret values
  set_fact:
    db_user_password: "{{ secrets.db_user_password | default('') }}"
    db_root_password: "{{ secrets.db_root_password | default('') }}"
    jwt_secret: "{{ secrets.jwt_secret | default('') }}"
    # Add more secrets if needed
  tags: env_config
