---
- name: Ensure MySQL databases are created
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ root_password }}"
  loop: "{{ dbs }}"
  become: true

- name: Ensure MySQL user is created
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ emr_password }}"
    priv: "{{ item }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ root_password }}"
  loop: "{{ dbs }}"
  become: true

- name: Flush privileges to apply changes
  community.mysql.mysql_query:
    login_user: root
    login_password: "{{ root_password }}"
    query: "FLUSH PRIVILEGES;"
  become: true
