- name: Create EMR DB user
  community.mysql.mysql_user:
    name: "{{ emr_db_user }}"
    password: "{{ emr_db_password }}"
    priv: 'emr_db.*:ALL'
    host: "%"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"

- name: Create Billing DB user
  community.mysql.mysql_user:
    name: "{{ billing_db_user }}"
    password: "{{ billing_db_password }}"
    priv: 'billing_db.*:ALL'
    host: "%"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"

- name: Create Demo DB user
  community.mysql.mysql_user:
    name: "{{ demo_db_user }}"
    password: "{{ demo_db_password }}"
    priv: 'demo_db.*:ALL'
    host: "%"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
