- name: Create EMR database
  mysql_db:
    name: emr_db
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create EMR DB user
  mysql_user:
    name: "{{ emr_db_user }}"
    password: "{{ emr_db_password }}"
    host: "%"
    priv: "emr_db.*:ALL"
    state: present

- name: Create Billing database
  mysql_db:
    name: billing_db
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create Billing DB user
  mysql_user:
    name: "{{ billing_db_user }}"
    password: "{{ billing_db_password }}"
    host: "%"
    priv: "billing_db.*:ALL"
    state: present

- name: Create Demo database
  mysql_db:
    name: demo_db
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create Demo DB user
  mysql_user:
    name: "{{ demo_db_user }}"
    password: "{{ demo_db_password }}"
    host: "%"
    priv: "demo_db.*:ALL"
    state: present
