- name: Reload demo.service with updated env
  block:
    - name: Reload systemd daemon
      command: systemctl daemon-reexec

    - name: Restart Spring Boot service
      systemd:
        name: demo.service
        state: restarted
        enabled: true
