- name: Ensure basic packages are installed
  apt:
    name:
      - vim
      - curl
      - wget
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install MySQL Python bindings (PyMySQL) using apt
  apt:
    name: python3-pymysql
    state: present

- name: Install psycopg2 for PostgreSQL modules
  apt:
    name: python3-psycopg2
    state: present

- import_tasks: set_system_env.yml
