- name: Write DB credentials to environment file
  copy:
    dest: /etc/myapp.env
    content: |
      EMR_DB_USER={{ emr_db_user }}
      EMR_DB_PASSWORD={{ emr_db_password }}
      BILLING_DB_USER={{ billing_db_user }}
      BILLING_DB_PASSWORD={{ billing_db_password }}
      DEMO_DB_USER={{ demo_db_user }}
      DEMO_DB_PASSWORD={{ demo_db_password }}
    owner: root
    group: root
    mode: '0600'
  notify: Reload demo.service with updated env

- name: Ensure demo.service uses /etc/myapp.env
  lineinfile:
    path: /etc/systemd/system/demo.service
    regexp: '^EnvironmentFile='
    line: 'EnvironmentFile=/etc/myapp.env'
    insertafter: '^ExecStart='
    notify: Reload demo.service with updated env
