- name: Set system-wide environment variables for DB credentials
  copy:
    dest: /etc/profile.d/db_env.sh
    content: |
      export EMR_DB_USER={{ emr_db_user }}
      export EMR_DB_PASSWORD={{ emr_db_password }}
      export BILLING_DB_USER={{ billing_db_user }}
      export BILLING_DB_PASSWORD={{ billing_db_password }}
      export DEMO_DB_USER={{ demo_db_user }}
      export DEMO_DB_PASSWORD={{ demo_db_password }}
    owner: root
    group: root
    mode: '0644'
  notify: Reload environment
# This task sets system-wide environment variables for database credentials
# and notifies the handler to reload the environment.


