---
- name: Provision DB for EMR
  hosts: demo
  become: yes
  gather_facts: false
  vars:
    env_name: testing
    service_name: demo
  pre_tasks:
  - name: Load env config
    import_tasks: ../tasks/load_env_config.yml
    

  - name: Debug DB variables (check if loaded correctly)
    debug:
        msg:
          - "DB User: {{ db_user }}"
          - "Databases: {{ database }}"
          - "Root Password: {{ db_password | default('not loaded') }}"
  tasks:
    - name: Export .env file to remote VPS
      import_tasks: ../tasks/export_env_file.yml
  roles:
    - mysql
