---
- name: Provision DB for EMR
- hosts: emr
  become: yes
  gather_facts: false
  vars:
    env_name: testing
    service_name: emr
  tasks:
    - import_tasks: ../tasks/load_env_config.yml
  roles:
    - mysql
