---
- name: Provision DB for EMR
  hosts: emr
  become: yes
  gather_facts: false
  vars:
    env_name: testing
    service_name: emr
  pre_tasks:
  - name: Load env config
    import_tasks: ../tasks/load_env_config.yml
  pre_tasks:
  - name: set env variables
    import_tasks: ../tasks/export_env_file.yml

  - name: Debug DB variables (check if loaded correctly)
    debug:
        msg:
          - "DB User: {{ db_user }}"
          - "Databases: {{ databases }}"
          - "Root Password: {{ db_password | default('not loaded') }}"
  # roles:
  #   - mysql
