- name: Rotate DB User Passwords
  hosts: dbservers
  become: yes
  tasks:
    - import_role:
        name: mysql
        tasks_from: rotate_passwords.yml
    - import_role:
        name: postgresql
        tasks_from: rotate_passwords.yml
